import random
import time

import requests
from bs4 import BeautifulSoup
from selenium import webdriver


def firstLink(topic):
    search = topic
    url = 'https://www.google.com/search'

    headers = {
        'Accept': '*/*',
        'Accept-Language': 'en-US,en;q=0.5',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82',
    }
    parameters = {'q': search}

    content = requests.get(url, headers=headers, params=parameters).text
    soup = BeautifulSoup(content, 'html.parser')

    search = soup.find(id='search')
    first_link = search.find('a')
    try:
        link = first_link['href']
        print(link)
        if link != "#":
            perform_search(link)
        # Process the link further
    except KeyError:
        print("The link element does not have an 'href' attribute.")
        # Handle the situation gracefully, e.g., by skipping this link


def perform_search(firstURL):
    chrome_options = webdriver.ChromeOptions()

    # Set user data directory
    chrome_options.add_argument("--user-data-dir=/Users/simson/Library/Application Support/Google/Chrome/")

    # Create a new instance of Chrome webdriver with ChromeOptions
    driver = webdriver.Chrome(options=chrome_options)

    # Navigate to the login page

    try:
        driver.get(firstURL)
        time.sleep(1)

    except Exception as e:
        print("Error clicking on the first link:", e)
        driver.quit()


if __name__ == "__main__":

    # List of random topics to search for
    negative_topics = [
        "Coping with Work Failure and overcoming setbacks",
        "Rebuilding Self-Assurance after experiencing loss",
        "Navigating Solutions during Financial Crisis",
        "Dealing with Relationship Challenges and seeking guidance",
        "Managing Health Issues and finding support",
        "Dealing with Loneliness and seeking companionship",
        "Handling Rejection with a positive mindset",
        "Understanding Symptoms and Treatments for Depression",
        "Managing Anxiety Attacks and seeking assistance",
        "Techniques for Stress Management and coping",
        "Dealing with Life Disappointments",
        "Strategies for Success after Academic Setbacks",
        "Coping with Grief and seeking comfort",
        "Recovering from Betrayal and rebuilding trust",
        "Overcoming Insecurity and building confidence",
        "Managing Overwhelm and seeking balance",
        "Preventing Burnout and achieving balance",
        "Improving Self-Esteem and self-worth",
        "Navigating Challenges of Unemployment",
        "Support for Disabilities and finding resources",
        "Coping with Isolation and seeking connection",
        "Healing from Trauma and seeking therapy",
        "Navigating Divorce and seeking legal guidance",
        "Learning from Mistakes and moving forward",
        "Finding Hope during Difficult Times",
        "Overcoming Addiction and seeking treatment",
        "Seeking Support for Abuse and finding help",
        "Managing Debt and financial planning",
        "Pursuing Dreams and setting goals",
        "Dealing with Bullying and finding assistance",
        "Addressing Discrimination and seeking justice",
        "Coping with Powerlessness and seeking empowerment",
        "Grieving Loss of Loved Ones and seeking solace",
        "Overcoming Self-Doubt and building confidence",
        "Dealing with Imposter Syndrome and seeking validation",
        "Seeking Justice in the face of Injustice",
        "Overcoming Fear of Failure and taking risks",
        "Navigating Existential Crisis and seeking purpose",
        "Overcoming Feelings of Worthlessness and seeking validation",
        "Rebuilding Trust after Friend Betrayal",
        "Addressing Inferiority Complex and building self-worth",
        "Finding Optimism in Pessimistic Times",
        "Breaking Free from Feeling Stuck and seeking change",
        "Coping with Overthinking and practicing mindfulness",
        "Managing Rumination and seeking therapy",
        "Dealing with Dysfunctional Family Dynamics",
        "Healing from Heartbreak and seeking closure",
        "Overcoming Envy and practicing gratitude",
        "Addressing Recurring Nightmares and seeking therapy",
        "Coping with Social Rejection and finding belonging",
        "Healing from Feeling Unloved and seeking support",
        "Overcoming Self-Loathing and practicing self-compassion",
        "Navigating Unrequited Love and seeking closure",
        "Overcoming Self-Sabotage and increasing self-awareness",
        "Coping with Feelings of Helplessness and seeking empowerment",
        "Addressing Perfectionism and seeking balance",
        "Managing Symptoms of Obsessive Compulsive Disorder",
        "Finding Light in Dark Situations",
        "Seeking Help for Persistent Sadness",
        "Challenging Catastrophic Thinking and seeking therapy",
        "Overcoming Feeling Unwanted and seeking validation",
        "Addressing Crippling Fear and seeking support",
        "Navigating Existential Dread and finding purpose",
        "Seeking Appreciation despite Feeling Unappreciated",
        "Coping with Shame and practicing self-forgiveness",
        "Exploring Self-Discovery to Fill Emptiness",
        "Managing Chronic Illness and seeking support",
        "Addressing Job Insecurity and seeking career guidance",
        "Coping with Impending Doom Thoughts and seeking therapy",
        "Overcoming Fear of Rejection and seeking validation",
        "Dealing with Regret and practicing self-forgiveness",
        "Healing Emotional Pain and seeking therapy",
        "Finding Motivation during Unmotivated Times",
        "Challenging Dark Thoughts with Positivity",
        "Replacing Negative Self-Talk with self-affirmations",
        "Overcoming Fear of the Unknown and seeking adventure",
        "Healing from Emotional Abuse and seeking therapy",
        "Addressing Unresolved Trauma and seeking closure",
        "Finding Direction after Loss of Direction",
        "Seeking Happiness amidst Unhappiness",
        "Reconnecting and Overcoming Disconnection",
        "Breaking Free from Feeling Trapped and seeking change",
        "Navigating Relationship Failures and seeking closure",
        "Healing from Emotional Neglect and seeking therapy",
        "Overcoming Feeling of Abandonment and seeking support",
        "Addressing Fear of Abandonment and seeking reassurance",
        "Coping with Feelings of Inadequacy and seeking validation",
        "Managing Paranoia and seeking therapy",
        "Overcoming Feeling of Invisibility and seeking validation"
    ]
    positive_topics = [
        "Tips and Strategies for Achieving Success at Work",
        "Achieving Personal and Professional Success",
        "Strategies for Attaining Financial Stability",
        "Advice on Building and Maintaining Healthy Relationships",
        "Tips for Wellness and Fitness for a Balanced Lifestyle",
        "Finding Happiness in Everyday Life",
        "Practicing Gratitude for Improved Well-Being",
        "Cultivating Optimism during Adversity",
        "Boosting Confidence through Self-Improvement",
        "Techniques for Personal Growth and Self-Improvement",
        "Advice on Love and Affection in Relationships",
        "Finding Fulfillment in Life's Pursuits",
        "Bringing Joy into Daily Activities",
        "Seeking Adventure and Excitement",
        "Fostering Creativity in Various Life Areas",
        "Building Friendship and Social Connections",
        "Developing Compassion for Others",
        "Practicing Empathy in Relationships",
        "Cultivating Generosity and Community Support",
        "Acts of Kindness and Gestures Toward Others",
        "Attaining Peace of Mind through Mindfulness",
        "Striving for Contentment in Life",
        "Seeking Satisfaction in Personal and Professional Goals",
        "Appreciation for Life's Blessings and Opportunities",
        "Holding onto Hope during Challenges",
        "Embracing Courage in Adversity",
        "Building Resilience for Mental and Emotional Strength",
        "Seeking Inspiration for Creativity and Motivation",
        "Finding Motivation for Personal and Professional Goals",
        "Inner Peace through Meditation and Reflection",
        "Embracing Enthusiasm for Life's Opportunities",
        "Cultivating a Positive Mindset and Outlook",
        "Practicing Self-Love and Self-Care",
        "Expressing Gratitude for Abundance in Life",
        "Attracting Abundance through Positive Thinking",
        "Boosting Self-Confidence through Affirmations",
        "Taking Pride in Personal Achievements",
        "Commitment to Personal Growth and Development",
        "Maintaining an Optimistic Outlook on Life",
        "Spreading Smiles and Positivity",
        "Enjoying the Benefits of Laughter Therapy",
        "Creating Warmth and Connection in Relationships",
        "Success Tips and Advice for Relationships",
        "Adopting a Healthy Lifestyle for Well-Being",
        "Practices for Mental and Physical Health",
        "Building a Supportive Community Around You",
        "Exploring Fulfilling Hobbies for Relaxation",
        "Seeking Meaningful Connections with Others",
        "Empowerment Strategies for Personal Growth",
        "Resources and Tools for Personal Development",
        "Working Towards Financial Freedom",
        "Inner Harmony through Mindfulness Practices",
        "Visualizing a Bright Future for Motivation",
        "Strategies for Dream Fulfillment and Goal-Setting",
        "Embracing Exciting Opportunities in Life",
        "Embarking on Adventures for New Experiences",
        "Embracing New Beginnings with Positivity",
        "Surrounding Yourself with Positive Energy",
        "Radiating Positivity and Good Vibes",
        "Kindness and Compassion towards Others",
        "Graciousness in Daily Interactions",
        "Building Strength through Life's Challenges",
        "Gaining Wisdom from Life Experiences",
        "Exploring Spirituality for Inner Peace",
        "Finding Balance in All Aspects of Life",
        "Harmony in Relationships and Daily Life",
        "Embracing Serendipity in Life's Surprises",
        "Belief in Miracles and Their Power",
        "Manifesting Dreams and Goals",
        "Euphoria and Its Impact on Well-Being",
        "Finding Bliss in Everyday Moments",
        "Maintaining High Spirits during Difficult Times",
        "Celebrating Life's Achievements and Milestones",
        "Adopting an Optimistic Attitude towards Life",
        "Faith in Oneself and Higher Powers",
        "Building Trust in Relationships and Life",
        "Attracting Good Fortune through Positivity",
        "Finding Comfort in Challenging Situations",
        "Counting Blessings and Practicing Gratitude",
        "Welcoming Fortunate Events with Open Arms",
        "Expressing Affection towards Loved Ones",
        "Practices for Emotional and Physical Healing",
        "Renewing Mind, Body, and Spirit",
        "Revitalization Techniques for Energy and Vitality",
        "Attracting Abundant Blessings through Gratitude",
        "Gratefulness for Life's Many Blessings",
        "Acts of Kindness towards Strangers",
        "Generous Gestures and Acts of Giving"

    ]
    depressed_topics = [
        "Expressing Sympathy for Those Experiencing Depression",
        "Navigating Through the Overwhelming Feelings of Sadness and Hopelessness Associated with Depression",
        "Accessing Strategies and Resources for Coping with Depression",
        "Addressing Loneliness and Finding Healthy Coping Mechanisms",
        "Managing Anxiety Attacks and Finding Supportive Techniques",
        "Affirming Self-Worth and the Availability of Support",
        "Exploring Online Therapy Options for Convenient Support",
        "Increasing Awareness of Depression Symptoms for Early Intervention",
        "Utilizing Coping Strategies for Managing Sadness",
        "Engaging in Support Groups for Depression",
        "Accessing Suicide Prevention Hotlines for Immediate Help",
        "Seeking Counseling Services for Tailored Support",
        "Exploring Mental Health Resources for Information and Support",
        "Finding Hope and Purpose in Life despite Depression",
        "Improving Sleep Hygiene for Better Rest",
        "Utilizing Cognitive Behavioral Therapy for Challenging Negative Thoughts",
        "Incorporating Mindfulness and Meditation into Daily Life",
        "Navigating Relationships Despite Depression's Challenges",
        "Understanding Antidepressant Medications and Treatment Options",
        "Seeking Support from Friends and Family",
        "Exploring Self-Help Books for Additional Insights",
        "Incorporating Physical Activity for Mood Improvement",
        "Finding Purpose and Meaning in Life",
        "Processing Loss and Grief with Support",
        "Accessing Immediate Help for Suicidal Thoughts",
        "Exploring Financial Assistance Options for Treatment",
        "Optimizing Nutrition for Mental Health",
        "Utilizing Self-Help Strategies for Depression",
        "Building a Support Network",
        "Addressing Mental Health Stigma",
        "Engaging in Online Depression Communities",
        "Expressing Emotions through Art or Writing",
        "Seeking Joy and Gratitude",
        "Creating a Personalized Self-Care Routine",
        "Understanding the Biology of Depression",
        "Overcoming Barriers to Seeking Help",
        "Managing Depression in School or Work Environments",
        "Establishing Healthy Boundaries",
        "Exploring Alternative Therapies for Depression",
        "Identifying Triggers and Developing Coping Mechanisms",
        "Challenging Negative Thought Patterns",
        "Building Resilience",
        "Seeking Professional Help and Support",
        "Addressing Trauma's Role in Depression",
        "Finding Affordable Mental Health Care",
        "Developing Healthy Habits for Well-Being",
        "Seeking Social Support",
        "Managing Depression and Chronic Pain",
        "Utilizing Journaling for Emotional Processing",
        "Validating the Challenges of Living with Depression",
        "Understanding the Mind-Body Connection",
        "Overcoming Perfectionism and Self-Criticism",
        "Developing Coping Skills for Difficult Situations",
        "Exploring Spirituality and Faith",
        "Finding Meaning in Suffering",
        "Creating Healthy Relationships",
        "Managing Depression During Pregnancy",
        "Recognizing and Addressing Postpartum Depression",
        "Coping with Seasonal Affective Disorder",
        "Addressing Depression in Older Adults",
        "Understanding Childhood Trauma's Impact on Mental Health",
        "Managing Stress in Daily Life",
        "Establishing Healthy Boundaries",
        "Exploring the Genetic Component of Depression",
        "Overcoming Barriers to Seeking Help",
        "Setting Realistic Goals for Recovery",
        "Incorporating Exercise for Mental Health",
        "Practicing Self-Compassion and Acceptance",
        "Aligning Career Choices with Mental Health Needs",
        "Navigating the Healthcare System",
        "Creating a Crisis Plan for Emergencies",
        "Understanding the Link Between Substance Abuse and Depression",
        "Supporting a Loved One with Depression",
        "Addressing Mental Health Stigma",
        "Building Resilience in Children and Adolescents",
        "Exploring the Connection Between Trauma and Depersonalization Disorder",
        "Understanding the Role of Trauma Narratives in Healing",
        "Exploring the Impact of Childhood Neglect on Adult Mental Health",
        "Understanding the Role of Attachment Styles in Relationships",
        "Coping with Feelings of Jealousy and Envy",
        "Dealing with Identity Crises",
        "Understanding the Impact of Societal Pressures on Mental Health",
        "Coping with Workplace Stress and Burnout",
        "Exploring the Connection Between Financial Stress and Mental Health",
        "Understanding the Effects of Discrimination on Mental Well-Being",
        "Coping with Imposter Syndrome",
        "Exploring the Link Between Creativity and Mental Illness",
        "Coping with Chronic Feelings of Emptiness",
        "Understanding the Impact of Negative Self-Talk",
        "Coping with Body Image Issues",
        "Exploring the Connection Between Trauma and Dissociation",
        "Coping with Panic Attacks",
        "Understanding the Impact of Childhood Abuse on Adult Relationships",
        "Coping with Chronic Fatigue",
        "Exploring the Link Between Genetics and Addiction",
        "Coping with Feelings of Inadequacy",
        "Understanding the Connection Between Trauma and Personality Disorders",
        "Coping with Feelings of Irritability and Anger",
        "Exploring the Connection Between Chronic Stress and Inflammation",
        "Understanding the Impact of Emotional Neg",
        "Communicating About Depression with Friends and Family",
        "Books Offering Strategies for Overcoming Depression",
        "Exercises to Boost Mood and Improve Mental Health",
        "Discovering Purpose and Meaning in Life",
        "Navigating Through Loss and Grief",
        "Seeking Help for Suicidal Thoughts and Urges",
        "Finding Financial Assistance for Mental Health Treatment",
        "Nutrition and Dietary Tips for Mental Health",
        "Self-Help Strategies for Coping with Depression",
        "Building a Support System for Mental Health",
        "Understanding and Addressing the Stigma of Mental Illness",
        "Engaging in Online Depression Forums and Communities",
        "Utilizing Art or Writing for Emotional Expression",
        "Finding Joy in Everyday Moments",
        "Developing a Personalized Self-Care Routine",
        "Understanding the Biological Basis of Depression",
        "Gaining Motivation to Seek Help for Depression",
        "Managing Depression in School or Workplace Settings",
        "Establishing Healthy Boundaries for Mental Well-Being",
        "Exploring Alternative Therapies for Depression Treatment",
        "Identifying Triggers for Depressive Episodes",
        "Breaking the Cycle of Negative Thoughts in Depression",
        "Building Resilience During Difficult Times",
        "Recognizing the Benefits of Professional Help for Depression",
        "Understanding Trauma's Role in Depression",
        "Finding Affordable Mental Health Care Options",
        "Developing Healthy Habits for Mental Well-Being",
        "Reaching Out for Social Support in Depression",
        "Coping with Chronic Pain Alongside Depression",
        "Utilizing Journaling for Emotional Release and Reflection",
        "Addressing Challenges of Living with Mental Illness",
        "Exploring the Link Between Physical and Mental Health",
        "Overcoming Perfectionism and Self-Criticism in Depression",
        "Developing Coping Skills for Difficult Situations in Depression",
        "Exploring Spirituality and Faith as Sources of Support",
        "Finding Meaning and Purpose in Adversity",
        "Breaking Free from Negative Relationships Impacting Mental Health",
        "Managing Depression During Pregnancy",
        "Understanding Postpartum Depression and Seeking Support",
        "Coping with Seasonal Affective Disorder (SAD)",
        "Dealing with Depression in Older Adults",
        "Exploring the Impact of Childhood Trauma on Mental Health",
        "Managing Stress in Daily Life for Mental Well-Being",
        "Establishing Healthy Boundaries for Mental Health",
        "Understanding the Genetic Component of Depression",
        "Overcoming Barriers to Seeking Help for Depression",
        "Setting Realistic Goals for Depression Recovery",
        "Recognizing the Benefits of Exercise for Mental Health",
        "Practicing Self-Compassion and Acceptance in Depression",
        "Exploring Career Options Aligned with Mental Health Needs",
        "Navigating the Healthcare System for Mental Health Support",
        "Creating a Crisis Plan for Mental Health Emergencies",
        "Understanding the Link Between Substance Abuse and Depression",
        "Supporting a Loved One with Depression",
        "Navigating Societal Stigma Surrounding Mental Illness",
        "Building Resilience in Children and Adolescents",
        "Exploring the Connection Between Trauma and Addiction",
        "Coping with a Recent Diagnosis of Depression",
        "Finding Purpose After Experiencing Loss",
        "Understanding the Impact of Social Media on Mental Health",
        "Rebuilding Self-Esteem After Setbacks",
        "Learning to Forgive Oneself for Past Mistakes",
        "Exploring Career Changes for Improved Mental Health",
        "Managing Depression While Traveling",
        "Understanding the Impact of Sleep on Mental Health",
        "Coping with Chronic Illness and Its Effect on Depression",
        "Finding Hope and Positivity in Challenging Times",
        "Exploring the Role of Therapy Animals in Mental Health Treatment",
        "Coping with Anniversaries of Traumatic Events",
        "Understanding the Connection Between Trauma and Dissociation",
        "Developing a Safety Plan for Managing Suicidal Thoughts",
        "Finding Joy in Hobbies and Interests for Mental Well-Being",
        "Overcoming Feelings of Social Isolation in Depression",
        "Exploring Mindfulness Practices for Emotional Health",
        "Navigating the Challenges of Dating with Depression",
        "Understanding the Impact of Childhood Neglect on Mental Health",
        "Coping with Depression During the Holiday Season",
        "Finding Purpose through Volunteer Work or Community Service",
        "Coping with the Loss of a Beloved Pet",
        "Exploring the Role of Exercise in Reducing Anxiety and Depression",
        "Managing Depression During Life Transitions",
        "Understanding the Benefits of Group Therapy for Depression",
        "Tips for Building and Sustaining Healthy Relationships in Depression",
        "Overcoming Obstacles to Seeking Therapy for Depression",
        "Exploring the Impact of Cultural Factors on Mental Health",
        "Coping with Family Stigma Surrounding Mental Illness",
        "Understanding the Link Between Trauma and Addiction",
        "Coping with Feelings of Survivor's Guilt",
        "Finding Meaning in Spiritual Practices for Mental Well-Being",
        "Exploring the Relationship Between Creativity and Mental Health",
        "Managing Depression While Providing Care for Others",
        "Understanding the Impact of Early Childhood Experiences on Mental Health",
        "Recognizing Symptoms of Depression",
        "Understanding the Root Causes of Chronic Sadness",
        "Implementing Coping Mechanisms for Feelings of Hopelessness",
        "Identifying and Challenging Negative Thought Patterns",
        "Coping with Feelings of Isolation and Loneliness",
        "Understanding the Effects of Social Withdrawal in Depression",
        "Managing Anxiety Attacks and Panic Symptoms",
        "Addressing Fear of Failure and Rejection",
        "Coping with Self-Doubt and Insecurity",
        "Overcoming Feelings of Worthlessness and Inadequacy",
        "Strategies for Improving Self-Esteem and Self-Image",
        "Seeking Professional Help for Depression",
        "Exploring Different Types of Therapy for Mental Health Support",
        "Understanding Medication Options for Treating Depression",
        "Engaging in Support Groups for Individuals with Depression",
        "Addressing the Stigma of Mental Illness in Society",
        "Communicating with Loved Ones About Depression",
        "Exploring the Connection Between Depression and Physical Health",
        "Coping with Traumatic Experiences and Their Aftermath",
        "Grieving the Loss of a Loved One and Coping with Bereavement",
        "Addressing Feelings of Numbness and Disconnection",
        "Managing Mood Swings and Emotional Fluctuations",
        "Exploring Existential Questions About Life and Purpose",
        "Coping with Overwhelming Responsibilities and Stressors",
        "Managing Depression Alongside Chronic Pain and Illness",
        "Finding Motivation to Engage in Daily Activities",
        "Addressing Insomnia and Sleep Disturbances in Depression",
        "Understanding the Role of Genetics in Mental Health",
        "Exploring the Impact of Childhood Trauma on Mental Health",
        "Dealing with Intrusive Thoughts and Rumination",
        "Exploring Alternative Therapies for Depression Treatment",
        "Understanding the Connection Between Diet and Mood",
        "Exploring the Relationship Between Exercise and Mental Health",
        "Engaging in Creative Outlets for Self-Expression and Healing",
        "Finding Meaning and Purpose in Life's Challenges",
        "Exploring Spirituality and Its Influence on Mental Well-Being",
        "Coping with Feelings of Guilt, Shame, and Regret",
        "Understanding and Disrupting Negative Thought Patterns",
        "Coping with Seasonal Affective Disorder (SAD) and Winter Blues",
        "Understanding the Impact of Trauma on Memory and Cognition",
        "Exploring the Role of Neurotransmitters in Depression",
        "Understanding the Effects of Stress on Mental Health",
        "Coping with Perfectionism and Unrealistic Expectations",
        "Understanding the Relationship Between Trauma and Addiction",
        "Managing Emotional Eating Habits in Depression",
        "Exploring the Impact of Childhood Neglect on Adult Mental Health",
        "Understanding the Role of Attachment Styles in Relationships",
        "Coping with Feelings of Jealousy, Envy, and Comparison",
        "Navigating Identity Crises and Self-Exploration",
        "Understanding the Impact of Societal Pressures on Mental Health",
        "Coping with Stress and Burnout in the Workplace",
        "Exploring the Link Between Financial Stress and Mental Health",
        "Understanding the Effects of Discrimination on Mental Well-Being",
        "Coping with Imposter Syndrome and Feelings of Inadequacy",
        "Exploring the Connection Between Creativity and Mental Illness",
        "Coping with Chronic Feelings of Emptiness and Nihilism",
        "Understanding the Impact of Negative Self-Talk on Mental Health",
        "Coping with Body Image Issues and Dysmorphic",
        "Exploring the Connection Between Trauma and Dissociation",
        "Coping with Panic Attacks and Anxiety Disorders",
        "Understanding the Impact of Childhood Abuse on Adult Relationships",
        "Coping with Chronic Fatigue and Exhaustion",
        "Exploring the Link Between Genetics and Addiction Disorders",
        "Coping with Feelings of Inadequacy and Self-Doubt",
        "Understanding the Connection Between Trauma and Personality Disorders",
        "Coping with Feelings of Irritability, Anger, and Hostility",
        "Exploring the Connection Between Chronic Stress and Inflammation",
        "Understanding the Impact of Emotional Neglect on Mental Well-Being",
        "Coping with Feelings of Overwhelm and Burnout",
        "Exploring the Connection Between Trauma and Eating Disorders",
        "Understanding the Link Between Childhood Trauma and Adult Mental Health",
        "Coping with Feelings of Despair and Hopelessness",
        "Exploring the Connection Between Trauma and Attachment Disorders",
        "Understanding the Role of Resilience in Overcoming Adversity",
        "Coping with Feelings of Powerlessness and Helplessness",
        "Exploring the Connection Between Trauma and Personality Development",
        "Understanding the Impact of Trauma Triggers on Emotional Regulation",
        "Coping with Feelings of Envy, Resentment, and Bitterness",
        "Exploring the Connection Between Trauma and Paranoia",
        "Understanding the Impact of Trauma on Cognitive Functioning",
        "Coping with Feelings of Sadness, Despair, and Despondency",
        "Exploring the Connection Between Trauma and Depersonalization Disorder",
        "Understanding the Role of Trauma Narratives in the Healing Process"
    ]

    healthy_topics = [
        "Incorporating gratitude into your daily routine",
        "Exploring mindfulness meditation techniques",
        "Tips for cultivating positive relationships",
        "Strategies for personal growth and development",
        "Finding joy in hobbies and interests",
        "Promoting mental and emotional resilience",
        "Drawing inspiration from nature",
        "Celebrating achievements and milestones",
        "Practicing acts of kindness and generosity",
        "Discovering purpose and meaning in life",
        "Engaging in acts of kindness and generosity",
        "Prioritizing self-care and self-love",
        "Cultivating a positive mindset and attitude",
        "Pursuing dreams and aspirations",
        "Building a supportive social network",
        "Exploring creativity and self-expression",
        "Nurturing physical health through exercise and nutrition",
        "Embracing the present moment",
        "Practicing forgiveness and letting go of negativity",
        "Developing resilience in the face of challenges",
        "Embracing optimism and hope",
        "Seeking personal fulfillment",
        "Fostering a sense of belonging and community",
        "Engaging in laughter and humor",
        "Investing in meaningful relationships",
        "Finding balance and harmony",
        "Embracing opportunities for growth and learning",
        "Creating a vision for the future",
        "Living authentically",
        "Finding beauty and inspiration in everyday life",
        "Choosing positivity and optimism",
        "Spreading joy and positivity",
        "Embracing diversity and inclusion",
        "Finding strength in vulnerability",
        "Practicing mindfulness in daily life",
        "Cultivating gratitude and appreciation",
        "Choosing kindness and compassion",
        "Nurturing inner peace and contentment",
        "Building a purposeful life",
        "Cultivating resilience and perseverance",
        "Embracing change with open arms",
        "Living with intention and purpose",
        "Choosing love over fear",
        "Finding fulfillment in helping others",
        "Nurturing creativity and innovation",
        "Fostering curiosity and exploration",
        "Living in alignment with values and beliefs",
        "Choosing happiness and fulfillment",
        "Finding inspiration in the world",
        "Building meaningful connections",
        "Creating a purposeful life",
        "Embracing opportunities for growth",
        "Choosing positivity in every situation",
        "Finding joy in simple pleasures",
        "Nurturing gratitude for life",
        "Living with passion and enthusiasm",
        "Building strength through challenges",
        "Embracing personal transformation",
        "Choosing to focus on the good",
        "Finding purpose in daily activities",
        "Nurturing a sense of belonging",
        "Creating a life of love, joy, and abundance",
        "Choosing to see beauty in oneself and others",
        "Fostering wonder and awe",
        "Embracing adventure and exploration",
        "Living authentically and true to oneself",
        "Being present and mindful",
        "Finding strength in adversity",
        "Nurturing compassion and empathy",
        "Creating a life of purpose and passion",
        "Embracing opportunities for self-discovery",
        "Choosing growth in every challenge",
        "Finding joy in the journey of self-improvement",
        "Nurturing optimism and hope",
        "Living with purpose and intention",
        "Choosing to focus on what truly matters",
        "Finding inspiration in nature's beauty",
        "Embracing creativity and self-expression",
        "Cultivating gratitude for life's blessings",
        "Nurturing meaningful relationships",
        "Approaching life with wonder and curiosity",
        "Finding joy in everyday moments",
        "Embracing opportunities for personal growth",
        "Living authentically and in alignment",
        "Letting go of negativity and embracing positivity",
        "Finding strength and resilience",
        "Nurturing inner peace and tranquility",
        "Creating a life of purpose and meaning",
        "Embracing opportunities for love and connection",
        "Focusing on abundance and gratitude",
        "Finding joy in the present moment",
        "Nurturing wonder and awe",
        "Living with passion and enthusiasm",
        "Approaching challenges as growth opportunities",
        "Finding beauty and inspiration in everyday life",
        "Embracing personal transformation",
        "Nurturing meaningful connections",
        "Creating a life of love, joy, and fulfillment",
        "Approaching life with optimism and positivity",
        "Finding purpose and meaning in every experience",
        "Embracing opportunities for growth and self-discovery",
        "Nurturing gratitude and appreciation for life",
        "Living authentically and in alignment",
        "Focusing on what truly matters in life",
        "Finding joy in simple pleasures",
        "Embracing opportunities for creativity",
        "Cultivating wonder and curiosity",
        "Nurturing meaningful relationships",
        "Seeing the good in oneself and others",
        "Finding inspiration in nature's beauty",
        "Embracing opportunities for personal growth",
        "Living with purpose and intention",
        "Approaching life with an open heart and mind",
        "Finding joy and fulfillment in self-discovery",
        "Nurturing gratitude for life's blessings",
        "Creating a life of love, purpose, and meaning",
        "Focusing on positivity and optimism",
        "Finding beauty in everyday moments",
        "Embracing opportunities for love and growth",
        "Nurturing wonder and curiosity",
        "Living with passion, purpose, and intention",
        "Approaching life with courage and resilience",
        "Finding strength in adversity",
        "Embracing opportunities for personal and spiritual growth",
        "Nurturing meaningful connections",
        "Creating a life of love, joy, and abundance",
        "Focusing on happiness, fulfillment, and meaning",
        "Finding peace, contentment, and gratitude",
        "Embracing creativity and self-expression",
        "Nurturing wonder and curiosity",
        "Approaching life with gratitude and appreciation",
        "Finding joy and fulfillment in everyday life",
        "Embracing opportunities for love, connection, and growth",
        "Nurturing wonder and curiosity",
        "Living with passion, purpose, and intention",
        "Approaching life with an attitude of gratitude",
        "Finding joy, beauty, and inspiration in everyday moments",
        "Embracing opportunities for personal growth and development",
        "Nurturing meaningful connections and relationships",
        "Creating a life of love, purpose, and meaning",
        "Approaching life with optimism, positivity, and resilience",
        "Finding strength and courage in the face of adversity",
        "Embracing opportunities for personal and spiritual growth",
        "Nurturing meaningful connections and relationships",
        "Creating a life of love, joy, and abundance",
        "Approaching life with an attitude of gratitude",
        "Finding joy and fulfillment in everyday experiences",
        "Embracing opportunities for creativity and self-expression",
        "Nurturing gratitude and appreciation for life's blessings",
        "Living authentically and in alignment with values",
        "Approaching life with an open heart, curious mind, and positive outlook",
        "Finding joy, beauty, and inspiration in everyday moments",
        "Embracing opportunities for growth, learning, and self-discovery",
        "Nurturing wonder, curiosity, and awe for the world around"
    ]
    i = 0
    # Loop indefinitely
    while i < 500:
        # choosing mixed topics
        random_array = random.choices([negative_topics, positive_topics, depressed_topics, healthy_topics],
                                      weights=[3, 1, 3, 1])[0]

        # Choosing a bad/depressed topic from a pool of array
        not_nice_topic_array = random.choices([negative_topics, depressed_topics], weights=[1, 1])[0]
        not_nice_topic = random.choice(not_nice_topic_array)

        # Choosing a good topic from a pool of array
        nice_topic_array = random.choices([positive_topics, healthy_topics], weights=[1, 1])[0]
        nice_topic = random.choice(nice_topic_array)

        # Choosing truly random topic
        random_topic = random.choice(random_array)
        print("Performing search on:", random_topic, i)
        firstLink(random_topic)
        time.sleep(2)
        i += 1
